version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: quiz-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz_db
      MYSQL_USER: quizuser
      MYSQL_PASSWORD: 123mamad
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - quiz-network

  backend:
    build: .
    container_name: quiz-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/quiz_db
      SPRING_DATASOURCE_USERNAME: quizuser
      SPRING_DATASOURCE_PASSWORD: 123mamad
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8000:8000"
    networks:
      - quiz-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  quiz-network:
    driver: bridge

volumes:
  mysql-data:
